COVALENT_BOND_DICT = {
    "ALA":
    [
        ('N', 'CA'),
        ('N', 'H'),
        ('CA', 'C'),
        ('CA', 'CB'),
        ('CA', 'HA'),
        ('C', 'O'),
        ('C', 'OXT'),
        ('CB', 'HB1'),
        ('CB', 'HB2'),
        ('CB', 'HB3'),
        ('N', 'H3'),
        ('N', 'H2'),
    ],

    "ARG":
    [
        ('N', 'CA'),
        ('N', 'H'),
        ('CA', 'C'),
        ('CA', 'CB'),
        ('CA', 'HA'),
        ('C', 'O'),
        ('C', 'OXT'),
        ('CB', 'CG'),
        ('CB', 'HB2'),
        ('CB', 'HB3'),
        ('CG', 'CD'),
        ('CG', 'HG2'),
        ('CG', 'HG3'),
        ('CD', 'NE'),
        ('CD', 'HD2'),
        ('CD', 'HD3'),
        ('NE', 'CZ'),
        ('NE', 'HE'),
        ('CZ', 'NH1'),
        ('CZ', 'NH2'),
        ('NH1', 'HH11'),
        ('NH1', 'HH12'),
        ('NH2', 'HH21'),
        ('NH2', 'HH22'),
        ('N', 'H3'),
        ('N', 'H2'),
    ],

    "ASN":
    [
        ('N', 'CA'),
        ('N', 'H'),
        ('CA', 'C'),
        ('CA', 'CB'),
        ('CA', 'HA'),
        ('C', 'O'),
        ('C', 'OXT'),
        ('CB', 'CG'),
        ('CB', 'HB2'),
        ('CB', 'HB3'),
        ('CG', 'OD1'),
        ('CG', 'ND2'),
        ('ND2', 'HD21'),
        ('ND2', 'HD22'),
        ('N', 'H3'),
        ('N', 'H2'),
    ],

    "ASP":
    [
        ('N', 'CA'),
        ('N', 'H'),
        ('CA', 'C'),
        ('CA', 'CB'),
        ('CA', 'HA'),
        ('C', 'O'),
        ('C', 'OXT'),
        ('CB', 'CG'),
        ('CB', 'HB2'),
        ('CB', 'HB3'),
        ('CG', 'OD1'),
        ('CG', 'OD2'),
        ('N', 'H3'),
        ('N', 'H2'),
    ],

    "CYS":
    [
        ('N', 'CA'),
        ('N', 'H'),
        ('CA', 'C'),
        ('CA', 'CB'),
        ('CA', 'HA'),
        ('C', 'O'),
        ('C', 'OXT'),
        ('CB', 'SG'),
        ('CB', 'HB2'),
        ('CB', 'HB3'),
        ('SG', 'HG'),
        ('N', 'H3'),
        ('N', 'H2'),
    ],

    "GLN":
    [
        ('N', 'CA'),
        ('N', 'H'),
        ('CA', 'C'),
        ('CA', 'CB'),
        ('CA', 'HA'),
        ('C', 'O'),
        ('C', 'OXT'),
        ('CB', 'CG'),
        ('CB', 'HB2'),
        ('CB', 'HB3'),
        ('CG', 'CD'),
        ('CG', 'HG2'),
        ('CG', 'HG3'),
        ('CD', 'OE1'),
        ('CD', 'NE2'),
        ('NE2', 'HE21'),
        ('NE2', 'HE22'),
        ('N', 'H3'),
        ('N', 'H2'),
    ],

    "GLU":
    [
        ('N', 'CA'),
        ('N', 'H'),
        ('CA', 'C'),
        ('CA', 'CB'),
        ('CA', 'HA'),
        ('C', 'O'),
        ('C', 'OXT'),
        ('CB', 'CG'),
        ('CB', 'HB2'),
        ('CB', 'HB3'),
        ('CG', 'CD'),
        ('CG', 'HG2'),
        ('CG', 'HG3'),
        ('CD', 'OE1'),
        ('CD', 'OE2'),
        ('N', 'H3'),
        ('N', 'H2'),
    ],

    "GLY":
    [
        ('N', 'CA'),
        ('N', 'H'),
        ('CA', 'C'),
        ('CA', 'HA2'),
        ('CA', 'HA3'),
        ('C', 'O'),
        ('C', 'OXT'),
        ('N', 'H3'),
        ('N', 'H2'),
    ],

    "HIS":
    [
        ('N', 'CA'),
        ('N', 'H'),
        ('CA', 'C'),
        ('CA', 'CB'),
        ('CA', 'HA'),
        ('C', 'O'),
        ('C', 'OXT'),
        ('CB', 'CG'),
        ('CB', 'HB2'),
        ('CB', 'HB3'),
        ('CG', 'ND1'),
        ('CG', 'CD2'),
        ('ND1', 'CE1'),
        ('ND1', 'HD1'),
        ('CD2', 'NE2'),
        ('CD2', 'HD2'),
        ('CE1', 'NE2'),
        ('CE1', 'HE1'),
        ('NE2', 'HE2'),
        ('N', 'H3'),
        ('N', 'H2'),
    ],

    "ILE":
    [
        ('N', 'CA'),
        ('N', 'H'),
        ('CA', 'C'),
        ('CA', 'CB'),
        ('CA', 'HA'),
        ('C', 'O'),
        ('C', 'OXT'),
        ('CB', 'CG1'),
        ('CB', 'CG2'),
        ('CB', 'HB'),
        ('CG1', 'CD1'),
        ('CG1', 'HG12'),
        ('CG1', 'HG13'),
        ('CG2', 'HG21'),
        ('CG2', 'HG22'),
        ('CG2', 'HG23'),
        ('CD1', 'HD11'),
        ('CD1', 'HD12'),
        ('CD1', 'HD13'),
        ('N', 'H3'),
        ('N', 'H2'),
    ],

    "LEU":
    [
        ('N', 'CA'),
        ('N', 'H'),
        ('CA', 'C'),
        ('CA', 'CB'),
        ('CA', 'HA'),
        ('C', 'O'),
        ('C', 'OXT'),
        ('CB', 'CG'),
        ('CB', 'HB2'),
        ('CB', 'HB3'),
        ('CG', 'CD1'),
        ('CG', 'CD2'),
        ('CG', 'HG'),
        ('CD1', 'HD11'),
        ('CD1', 'HD12'),
        ('CD1', 'HD13'),
        ('CD2', 'HD21'),
        ('CD2', 'HD22'),
        ('CD2', 'HD23'),
        ('N', 'H3'),
        ('N', 'H2'),
    ],

    "LYS":
    [
        ('N', 'CA'),
        ('N', 'H'),
        ('CA', 'C'),
        ('CA', 'CB'),
        ('CA', 'HA'),
        ('C', 'O'),
        ('C', 'OXT'),
        ('CB', 'CG'),
        ('CB', 'HB2'),
        ('CB', 'HB3'),
        ('CG', 'CD'),
        ('CG', 'HG2'),
        ('CG', 'HG3'),
        ('CD', 'CE'),
        ('CD', 'HD2'),
        ('CD', 'HD3'),
        ('CE', 'NZ'),
        ('CE', 'HE2'),
        ('CE', 'HE3'),
        ('NZ', 'HZ1'),
        ('NZ', 'HZ2'),
        ('NZ', 'HZ3'),
        ('N', 'H3'),
        ('N', 'H2'),
    ],

    "MET":
    [
        ('N', 'CA'),
        ('N', 'H'),
        ('CA', 'C'),
        ('CA', 'CB'),
        ('CA', 'HA'),
        ('C', 'O'),
        ('C', 'OXT'),
        ('CB', 'CG'),
        ('CB', 'HB2'),
        ('CB', 'HB3'),
        ('CG', 'SD'),
        ('CG', 'HG2'),
        ('CG', 'HG3'),
        ('SD', 'CE'),
        ('CE', 'HE1'),
        ('CE', 'HE2'),
        ('CE', 'HE3'),
        ('N', 'H3'),
        ('N', 'H2'),
    ],

    "PHE":
    [
        ('N', 'CA'),
        ('N', 'H'),
        ('CA', 'C'),
        ('CA', 'CB'),
        ('CA', 'HA'),
        ('C', 'O'),
        ('C', 'OXT'),
        ('CB', 'CG'),
        ('CB', 'HB2'),
        ('CB', 'HB3'),
        ('CG', 'CD1'),
        ('CG', 'CD2'),
        ('CD1', 'CE1'),
        ('CD1', 'HD1'),
        ('CD2', 'CE2'),
        ('CD2', 'HD2'),
        ('CE1', 'CZ'),
        ('CE1', 'HE1'),
        ('CE2', 'CZ'),
        ('CE2', 'HE2'),
        ('CZ', 'HZ'),
        ('N', 'H3'),
        ('N', 'H2'),
    ],

    "PRO":
    [
        ('N', 'CA'),
        ('N', 'CD'),
        ('N', 'H2'),
        ('CA', 'C'),
        ('CA', 'CB'),
        ('CA', 'HA'),
        ('C', 'O'),
        ('C', 'OXT'),
        ('CB', 'CG'),
        ('CB', 'HB2'),
        ('CB', 'HB3'),
        ('CG', 'CD'),
        ('CG', 'HG2'),
        ('CG', 'HG3'),
        ('CD', 'HD2'),
        ('CD', 'HD3'),
        ('N', 'H3'),
        ('N', 'H2'),
    ],

    "SER":
    [
        ('N', 'CA'),
        ('N', 'H'),
        ('CA', 'C'),
        ('CA', 'CB'),
        ('CA', 'HA'),
        ('C', 'O'),
        ('C', 'OXT'),
        ('CB', 'OG'),
        ('CB', 'HB2'),
        ('CB', 'HB3'),
        ('OG', 'HG'),
        ('N', 'H3'),
        ('N', 'H2'),
    ],

    "THR":
    [
        ('N', 'CA'),
        ('N', 'H'),
        ('CA', 'C'),
        ('CA', 'CB'),
        ('CA', 'HA'),
        ('C', 'O'),
        ('C', 'OXT'),
        ('CB', 'OG1'),
        ('CB', 'CG2'),
        ('CB', 'HB'),
        ('OG1', 'HG1'),
        ('CG2', 'HG21'),
        ('CG2', 'HG22'),
        ('CG2', 'HG23'),
        ('N', 'H3'),
        ('N', 'H2'),
    ],

    "TRP":
    [
        ('N', 'CA'),
        ('N', 'H'),
        ('CA', 'C'),
        ('CA', 'CB'),
        ('CA', 'HA'),
        ('C', 'O'),
        ('C', 'OXT'),
        ('CB', 'CG'),
        ('CB', 'HB2'),
        ('CB', 'HB3'),
        ('CG', 'CD1'),
        ('CG', 'CD2'),
        ('CD1', 'NE1'),
        ('CD1', 'HD1'),
        ('CD2', 'CE2'),
        ('CD2', 'CE3'),
        ('NE1', 'CE2'),
        ('NE1', 'HE1'),
        ('CE2', 'CZ2'),
        ('CE3', 'CZ3'),
        ('CE3', 'HE3'),
        ('CZ2', 'CH2'),
        ('CZ2', 'HZ2'),
        ('CZ3', 'CH2'),
        ('CZ3', 'HZ3'),
        ('CH2', 'HH2'),
        ('N', 'H3'),
        ('N', 'H2'),
    ],

    "TYR":
    [
        ('N', 'CA'),
        ('N', 'H'),
        ('CA', 'C'),
        ('CA', 'CB'),
        ('CA', 'HA'),
        ('C', 'O'),
        ('C', 'OXT'),
        ('CB', 'CG'),
        ('CB', 'HB2'),
        ('CB', 'HB3'),
        ('CG', 'CD1'),
        ('CG', 'CD2'),
        ('CD1', 'CE1'),
        ('CD1', 'HD1'),
        ('CD2', 'CE2'),
        ('CD2', 'HD2'),
        ('CE1', 'CZ'),
        ('CE1', 'HE1'),
        ('CE2', 'CZ'),
        ('CE2', 'HE2'),
        ('CZ', 'OH'),
        ('OH', 'HH'),
        ('N', 'H3'),
        ('N', 'H2'),
    ],

    "VAL":
    [
        ('N', 'CA'),
        ('N', 'H'),
        ('CA', 'C'),
        ('CA', 'CB'),
        ('CA', 'HA'),
        ('C', 'O'),
        ('C', 'OXT'),
        ('CB', 'CG1'),
        ('CB', 'CG2'),
        ('CB', 'HB'),
        ('CG1', 'HG11'),
        ('CG1', 'HG12'),
        ('CG1', 'HG13'),
        ('CG2', 'HG21'),
        ('CG2', 'HG22'),
        ('CG2', 'HG23'),
        ('N', 'H3'),
        ('N', 'H2'),
    ],
}


ATOM_DICT = {
    "ALA": ['N', 'CA', 'H', 'C', 'CB', 'HA', 'O', 'OXT', 'HB1', 'HB2', 'HB3', 'H3', 'H2'],
    "ARG": ['N', 'CA', 'H', 'C', 'CB', 'HA', 'O', 'OXT', 'CG', 'HB2', 'HB3', 'CD', 'HG2', 'HG3', 'NE', 'HD2', 'HD3', 'CZ', 'HE', 'NH1', 'NH2', 'HH11', 'HH12', 'HH21', 'HH22', 'H3', 'H2'],
    "ASN": ['N', 'CA', 'H', 'C', 'CB', 'HA', 'O', 'OXT', 'CG', 'HB2', 'HB3', 'OD1', 'ND2', 'HD21', 'HD22', 'H3', 'H2'],
    "ASP": ['N', 'CA', 'H', 'C', 'CB', 'HA', 'O', 'OXT', 'CG', 'HB2', 'HB3', 'OD1', 'OD2', 'H3', 'H2'],
    "CYS": ['N', 'CA', 'H', 'C', 'CB', 'HA', 'O', 'OXT', 'SG', 'HB2', 'HB3', 'HG', 'H3', 'H2'],
    "GLN": ['N', 'CA', 'H', 'C', 'CB', 'HA', 'O', 'OXT', 'CG', 'HB2', 'HB3', 'CD', 'HG2', 'HG3', 'OE1', 'NE2', 'HE21', 'HE22', 'H3', 'H2'],
    "GLU": ['N', 'CA', 'H', 'C', 'CB', 'HA', 'O', 'OXT', 'CG', 'HB2', 'HB3', 'CD', 'HG2', 'HG3', 'OE1', 'OE2', 'H3', 'H2'],
    "GLY": ['N', 'CA', 'H', 'C', 'HA2', 'HA3', 'O', 'OXT', 'H3', 'H2'],
    "HIS": ['N', 'CA', 'H', 'C', 'CB', 'HA', 'O', 'OXT', 'CG', 'HB2', 'HB3', 'ND1', 'CD2', 'CE1', 'HD1', 'NE2', 'HD2', 'HE1', 'HE2', 'H3', 'H2'],
    "ILE": ['N', 'CA', 'H', 'C', 'CB', 'HA', 'O', 'OXT', 'CG1', 'CG2', 'HB', 'CD1', 'HG12', 'HG13', 'HG21', 'HG22', 'HG23', 'HD11', 'HD12', 'HD13', 'H3', 'H2'],
    "LEU": ['N', 'CA', 'H', 'C', 'CB', 'HA', 'O', 'OXT', 'CG', 'HB2', 'HB3', 'CD1', 'CD2', 'HG', 'HD11', 'HD12', 'HD13', 'HD21', 'HD22', 'HD23', 'H3', 'H2'],
    "LYS": ['N', 'CA', 'H', 'C', 'CB', 'HA', 'O', 'OXT', 'CG', 'HB2', 'HB3', 'CD', 'HG2', 'HG3', 'CE', 'HD2', 'HD3', 'NZ', 'HE2', 'HE3', 'HZ1', 'HZ2', 'HZ3', 'H3', 'H2'],
    "MET": ['N', 'CA', 'H', 'C', 'CB', 'HA', 'O', 'OXT', 'CG', 'HB2', 'HB3', 'SD', 'HG2', 'HG3', 'CE', 'HE1', 'HE2', 'HE3', 'H3', 'H2'],
    "PHE": ['N', 'CA', 'H', 'C', 'CB', 'HA', 'O', 'OXT', 'CG', 'HB2', 'HB3', 'CD1', 'CD2', 'CE1', 'HD1', 'CE2', 'HD2', 'CZ', 'HE1', 'HE2', 'HZ', 'H3', 'H2'],
    "PRO": ['N', 'CA', 'CD', 'H2', 'C', 'CB', 'HA', 'O', 'OXT', 'CG', 'HB2', 'HB3', 'HG2', 'HG3', 'HD2', 'HD3', 'H3'],
    "SER": ['N', 'CA', 'H', 'C', 'CB', 'HA', 'O', 'OXT', 'OG', 'HB2', 'HB3', 'HG', 'H3', 'H2'],
    "THR": ['N', 'CA', 'H', 'C', 'CB', 'HA', 'O', 'OXT', 'OG1', 'CG2', 'HB', 'HG1', 'HG21', 'HG22', 'HG23', 'H3', 'H2'],
    "TRP": ['N', 'CA', 'H', 'C', 'CB', 'HA', 'O', 'OXT', 'CG', 'HB2', 'HB3', 'CD1', 'CD2', 'NE1', 'HD1', 'CE2', 'CE3', 'HE1', 'CZ2', 'CZ3', 'HE3', 'CH2', 'HZ2', 'HZ3', 'HH2', 'H3', 'H2'],
    "TYR": ['N', 'CA', 'H', 'C', 'CB', 'HA', 'O', 'OXT', 'CG', 'HB2', 'HB3', 'CD1', 'CD2', 'CE1', 'HD1', 'CE2', 'HD2', 'CZ', 'HE1', 'HE2', 'OH', 'HH', 'H3', 'H2'],
    "VAL": ['N', 'CA', 'H', 'C', 'CB', 'HA', 'O', 'OXT', 'CG1', 'CG2', 'HB', 'HG11', 'HG12', 'HG13', 'HG21', 'HG22', 'HG23', 'H3', 'H2'],
}


ATOM_LIST = ['N', 'CA', 'C', 'O', 'CB', 'CG', 'CD1', 'CD2', 'CE1', 'CE2', 'CZ',
             'OH', 'CD', 'NE', 'NE1', 'NE2', 'CE3', 'CZ2', 'CZ3', 'CH2', 'OE1',
             'OE2', 'OD1', 'OD2', 'CE', 'NZ', 'CG1', 'CG2','OG1', 'SD', 'ND1', 
             'SG', 'OG', 'ND2', 'DOD', 'EOE', 'FCD', 'FCE', 'YCD', 'YCE', 'CDL', 
             'CGV', 'NHR', 'H']

backbone_atoms = ['N', 'CA', 'C', 'O']

backbone_atom_indices = [0, 1, 2, 3]

atom_order = {atom: index for index, atom in enumerate(ATOM_LIST)}


ambiguous_mapping = {('D', 'OD1'): 'DOD',
                     ('D', 'OD2'): 'DOD',
                     ('E', 'OE1'): 'EOE',
                     ('E', 'OE2'): 'EOE',
                     ('F', 'CD1'): 'FCD',
                     ('F', 'CD2'): 'FCD',
                     ('F', 'CE1'): 'FCE',
                     ('F', 'CE2'): 'FCE',
                     ('Y', 'CD1'): 'YCD',
                     ('Y', 'CD2'): 'YCD',
                     ('Y', 'CE1'): 'YCE',
                     ('Y', 'CE2'): 'YCE',
                     ('L', 'CD1'): 'CDL',
                     ('L', 'CD2'): 'CDL',
                     ('V', 'CG1'): 'CGV',
                     ('V', 'CG2'): 'CGV', 
                     ('R', 'NH1'): 'NHR',
                     ('R', 'NH2'): 'NHR',}



RESIDUE_LIST = [
    "A",
    "R",
    "N",
    "D",
    "C",
    "Q",
    "E",
    "G",
    "H",
    "I",
    "L",
    "K",
    "M",
    "F",
    "P",
    "S",
    "T",
    "W",
    "Y",
    "V",
]

residue_order = {residue: i for i, residue in enumerate(RESIDUE_LIST)}

residue_mapping = {i: residue for i, residue in enumerate(RESIDUE_LIST)}

